version: '3.1'
services:
  db:
    image: postgres:14.1-alpine
    container_name: postgres-container
    restart: always
    environment:
      POSTGRES_PASSWORD: nogomet
      POSTGRES_DB: shop
    ports:
      - 5432:5432

