#spring:
#  autoconfigure:
#    exclude:
#    - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

spring:
  dataSource:
    url: jdbc:postgresql://localhost:5432/shop
    username: postgres
    password: nogomet



server:
  error:
    include-binding-errors: always
    include-message: always